vaadin.launch-browser=true
spring.application.name=ingredient
server.port=8082

vaadin.launch-browser=true
spring.application.name=ingredient

spring.datasource.url=jdbc:postgresql://10.0.1.85:5432/cosmetics
spring.datasource.username=cosmetics
spring.datasource.password=cosmetics
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
